Добавил возможность запуска командных файлов на язке PowerShell и др.
oscript-library/1commands pull request #2
Opened 2017-10-12 21:20 UTC by Berckk

Привет. 
Добавил указание расширения для командных файлов и возможность указания исполняемых файлов других сценарных языков.

2017-10-14 11:32 UTC, artbear requested changes
Хорошее дополнение библиотеки.
Но есть небольшие замечания.
Исправишь?

2017-10-14 11:32 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +	СоздатьФайл("","");
Здесь проще и понятнее написать `СоздатьФайл()`,  т.к. у этого метода оба параметр по умолчанию пустые строки.

2017-10-14 11:32 UTC, artbear commented on features/КомандныеФайлы.feature
> +    Когда Я устанавливаю приложение запуска "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
На Линуксе шаг упадет.
Предлагаю в реализацию шага `ЯУстанавливаюПриложениеЗапуска` добавить проверку на Линукс
Если Линукс, то отмечать шаг как пропущенный.

Это лучше, чем падающий тест

2017-10-14 11:32 UTC, artbear commented on features/КомандныеФайлы.feature
> +    И Я добавляю строку "echo PowerShell" в командный файл
Предлагаю добавить какую-нибудь уникальную для PowerShell-команду, а не псевдоним, который работает и для cmd.
Например, `Write-Host PowerShell`

2017-10-14 11:32 UTC, artbear commented on readme.md
> +КомандныйФайл.Создать(,".ps1");
Предлагаю указать явное пустое имя файла через
`КомандныйФайл.Создать("", ".ps1");`

PS пропуск параметра выглядит очень плохо

2017-10-14 11:32 UTC, artbear commented on src/КомандныйФайл.os
> +Функция Создать(Знач Путь = "",Знач Расширение="") Экспорт
Не хватает пробела перед вторым Знач

2017-10-14 11:32 UTC, artbear commented on src/КомандныйФайл.os
> +//   ПутьПриложения - Путь приложения (Строка)
Предлагаю добавить пример задания приложения в описание метода
`"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"`

2017-10-14 11:32 UTC, artbear commented on src/КомандныйФайл.os
> +	Если НЕ ПустаяСтрока(Приложение) Тогда
ИМХО здесь точнее `Если ЗначениеЗаполнено(Приложение) Тогда`
т.к. по умолчанию, без явной инициализации, `Приложение` равно `Неопределено`
И проверка на пустую строку сработает неверно.

2017-10-14 11:38 UTC, artbear commented
И последний вопрос - фичи прогонял?

2017-10-15 07:46 UTC, Berckk commented on features/КомандныеФайлы.feature
> +    Когда Я устанавливаю приложение запуска "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
Тут наверно для Линукса надо вообще весь сценарий проускать, но я не представляю как.

2017-10-15 07:54 UTC, Berckk commented
Фичи прогонял, но только на Windows.
То что при прогоне идет обращение к "C:\Program Files (x86)\OneScript\lib\1commands\src", а не к текущему каталогу проекта. Это как исправить?

2017-10-15 11:41 UTC, artbear commented on features/КомандныеФайлы.feature
> +    Когда Я устанавливаю приложение запуска "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
Внутри кода реализации вызови спец.метод `БДД.ВыполнитьШаг("Пропускаю шаг в Linux")`
[Документация на этот метод](https://github.com/artbear/1bdd#Программный-вызов-любого-шага-сценария)

ИМХО за счет того, что у нас нет реализации шага `Пропускаю шаг в Linux`, твой шаг/сценарий будет отмечен как пропущенный.

Попробуй.

2017-10-15 11:42 UTC, artbear commented
>То что при прогоне идет обращение к "C:\Program Files (x86)\OneScript\lib\1commands\src", а не к текущему каталогу проекта. Это как исправить?

@Berckk А откуда такая уверенность?
фичи настроены на прогон классов из исходников

2017-10-16 05:23 UTC, artbear commented
После последних своих правок тесты прогонял. Шаги пропускаются?

2017-10-16 05:29 UTC, artbear requested changes

2017-10-16 05:29 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +Функция ПропускаюШаг() Экспорт
1 Экспорт для этого метода не нужен.
2 Название метода предлагать поменять на более точное ПрпускаюШагНаLinux

2017-10-16 07:45 UTC, Berckk commented on features/КомандныеФайлы.feature
> +    Когда Я устанавливаю приложение запуска "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
В консоле добавляется сообщение "Пропускаю шаг в Linux".
В отчете bdd-log.xml шаг отмечается как  status="passed".

2017-10-16 07:53 UTC, Berckk commented on features/step_definitions/КомандныеФайлы.os
> +Функция ПропускаюШаг() Экспорт
С последними правками шаги пропускаются, но помечаются как успешные.

2017-10-16 08:53 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +	Если НЕ ЗначениеЗаполнено(ЭтоWindows) Тогда
Проверка `Если НЕ ЗначениеЗаполнено(ЭтоWindows) Тогда` в Линуксе всегда будет срабатывать и выполнять код внутри блока Если.
Т.к. значение ЭтоWindows будет Ложь, а ЗначениеЗаполнено(Ложь) всегда выдает Истину :(

Предлагаю исправить на `Если ЭтоWindows = Неопределено Тогда`

Сделай это последнее исправления и я принимаю пулл-реквест!

2017-10-16 09:52 UTC, artbear commented on features/КомандныеФайлы.feature
> +Контекст: Отключение отладки в логах
Оказывается, я пропустил неверную правку в фиче.

Контекст в фиче должен быть один, их не должно быть несколько.
Поэтому твое добавление контекста не валидно.

Предлагаю 
+ оставить один контекст.
```
Контекст: Отключение отладки в логах
      Допустим Я выключаю отладку лога с именем "oscript.lib.commands"
```
+ Добавить шаг `Я пропускаю этот сценарий в Линукс` как первый шаг сценария `Выполнение командного файла PowerShell`

2017-10-16 09:53 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +	Если ПропускаюШагВЛинукс() Тогда
Шаг `Код возврата командного файла равен 0` является универсальным.
В него не нужно вставлять проверку на линукс, т.к. этот шаг должен работать в линукс

2017-10-16 09:54 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +	Если ПропускаюШагВЛинукс() Тогда
Шаг `Вывод командного файла содержит "командный файл"` является универсальным.
В него не нужно вставлять проверку на линукс, т.к. этот шаг должен работать в линукс

2017-10-16 09:54 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +	Если ПропускаюШагВЛинукс() Тогда
Шаг `Я сообщаю содержимое командного файла` является универсальным.
В него не нужно вставлять проверку на линукс, т.к. этот шаг должен работать в линукс

2017-10-16 09:54 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +	Если ПропускаюШагВЛинукс() Тогда
Шаг `Я сообщаю содержимое файла "ИмяФайла"` является универсальным.
В него не нужно вставлять проверку на линукс, т.к. этот шаг должен работать в линукс

2017-10-16 09:55 UTC, artbear commented on features/step_definitions/КомандныеФайлы.os
> +Процедура ЯНЕПропускаюЭтотСценарийВЛинукс() Экспорт
Шаг `ЯНЕПропускаюЭтотСценарийВЛинукс` соответственно не нужен.
Его нужно удалить.

2017-10-16 09:55 UTC, artbear commented
Извини за придирчивость :)

2017-10-16 10:01 UTC, Berckk commented on features/step_definitions/КомандныеФайлы.os
> +	Если ПропускаюШагВЛинукс() Тогда
Да, но в сценарии с PowerShell в линуксе никого файла на этом шаге нет.
И тесты валятся.
Я поэтому и добавил проверку во все шаги.

2017-10-16 10:17 UTC, Berckk commented on features/step_definitions/КомандныеФайлы.os
> +	Если ПропускаюШагВЛинукс() Тогда
В линуксе можно создать файл с расширением ps1, т.к. расширение ни на что не влияет.
Но тесты выпадут с ошибкой на шаге `Я выполняю командный файл`, т.к. `Write-Host PowerShell` в линукс не отработает.
Поэтому я изначально спрашивал, как пропустить весь сценарий под линукс.

2017-10-16 10:25 UTC, artbear commented
Возможно, мы друг друга не поняли.
Что происходит с прогоном шагов/фич, когда ты вставил `БДД.ВыполнитьШаг("Пропустить шаг в Линукс");`
Шаги падают, или отмечаются как пропущенные, 
или успешно выполняются и далее выполняются следующие шаги??

2017-10-16 11:17 UTC, Berckk commented
Рассказываю все.
Запускаю в Windows, но в функции
`ПропускаюШагВЛинукс()`  добавляю `ЭтоWindows = Ложь;`
В каталоге проекта запускаю командную строку и выполняю `opm test`
в ответ выводится...
комментарий (серым цветом)  `Пропускаю шаг в Linux` и зеленым шаги.
Т.е. шаги успешно выполняются.

2017-10-16 13:16 UTC, artbear commented
Тут важно - именно последующие шаги из этого же сценария выполняются
или сценарий останавливается и запускаются шаги другого сценария?

можешь полный лог от `opm test` скинуть ?

2017-10-16 13:29 UTC, Berckk commented
Шаги выполняются, остановка не происходит.
![opm_test](https://user-images.githubusercontent.com/10886786/31614356-d292c3f2-b28e-11e7-9d04-18d334efbc4b.PNG)

2017-10-16 14:07 UTC, artbear commented
Все понятно, наша добавка с пропускаемым шагом на самом деле шаг не пропускает :(
Пока оставим так.
Я в 1бдд (прогонялку фич) добавлю ишуз для фиксации проблемы.

Сейчас сделаю последний код-ревью, если не увижу явных проблем, наконец-то замержу пулл-реквест

2017-10-16 14:10 UTC, artbear approved these changes

2017-10-16 14:11 UTC, merged

2017-10-16 14:11 UTC, artbear commented
@Berckk Большое спасибо!